package examples.gui;

import javax.swing.ButtonGroup;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author tadaki
 */
public class KanjiPatternsJFrame extends javax.swing.JFrame {

    private final GuiSimulation sys;

    /**
     * Creates new form NewJFrame
     */
    public KanjiPatternsJFrame() {
        initComponents();
        double temp[] = {0., 0.1, 0.5, 1., 5., 10., 50., 100.};
        sys = new GuiSimulation(drawPanel);
        sys.initImage();
        sys.setZeroTemperature(false);
        sys.setTemperature(temp[temp.length - 1]);

        ButtonGroup tempGroup = new ButtonGroup();
        for (double t : temp) {
            JCheckBoxMenuItem item
                    = new JCheckBoxMenuItem(String.valueOf(t));
            item.addActionListener(e -> setTemperature(t));
            temperatureMenu.add(item);
            tempGroup.add(item);
        }

        ButtonGroup pGroup = new ButtonGroup();
        int n = sys.getMaxNumPatterns();
        int pd[] = new int[n - 1];
        for (int i = 0; i < n-1; i++) {
            pd[i] = i + 1;
        }
        for (int p : pd) {
            JCheckBoxMenuItem item
                    = new JCheckBoxMenuItem(String.valueOf(p));
            item.addActionListener(e -> setPattern(p));
            patternsMenu.add(item);
            pGroup.add(item);
        }
    }

    private void setTemperature(double temperature) {
        if (temperature < 0.001) {
            sys.setZeroTemperature(true);
        } else {
            sys.setZeroTemperature(false);
            sys.setTemperature(temperature);
        }
    }

    private void setPattern(int p) {
        sys.stop();
        sys.setNumPatterns(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new examples.gui.DrawPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        stop = new javax.swing.JMenuItem();
        temperatureMenu = new javax.swing.JMenu();
        patternsMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Hopfield Model");

        drawPanel.setBackground(new java.awt.Color(204, 255, 204));
        drawPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        actionMenu.setText("Action");

        start.setText("start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        actionMenu.add(start);

        stop.setText("stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        actionMenu.add(stop);

        menuBar.add(actionMenu);

        temperatureMenu.setText("Temperature");
        menuBar.add(temperatureMenu);

        patternsMenu.setText("Patterns");
        menuBar.add(patternsMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        Thread runner = new Thread(sys);
        sys.start();
        runner.start();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        sys.stop();
    }//GEN-LAST:event_stopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KanjiPatternsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KanjiPatternsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KanjiPatternsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KanjiPatternsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KanjiPatternsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private examples.gui.DrawPanel drawPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu patternsMenu;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenuItem start;
    private javax.swing.JMenuItem stop;
    private javax.swing.JMenu temperatureMenu;
    // End of variables declaration//GEN-END:variables
}
